To add a Horizontal Pod Autoscaler (HPA) to your reddit-clone-deployment, you need to:

Ensure metrics server is installed in your Minikube cluster.

Apply an HPA YAML or use kubectl autoscale.

✅ Step 1: Install Metrics Server
minikube addons enable metrics-server


Check it's working:

kubectl get deployment metrics-server -n kube-system

✅ Step 2: Create the HPA YAML

Here’s a complete Horizontal Pod Autoscaler definition for your deployment. It will scale between 1 and 10 pods based on CPU usage:

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: reddit-clone-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: reddit-clone-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50

✅ Step 3: Apply the HPA

Save the above YAML to a file (e.g. hpa.yaml) and run:

kubectl apply -f hpa.yaml

Check the HPA status:

kubectl get hpa

🔄 Alternative (CLI): Use kubectl autoscale

If you prefer a one-liner instead of YAML:

kubectl autoscale deployment reddit-clone-deployment --cpu-percent=50 --min=1 --max=10
