apiVersion: v1
kind: Service
metadata:
  name: reddit-clone-service
  labels:
    app: reddit-clone
spec:
  selector:
    app: reddit-clone
  ports:
    - protocol: TCP
      port: 3000        # Service port inside the cluster
      targetPort: 3000
      nodePort: 31000 
  type: NodePort
